#!/usr/bin/env bash
#
# Install the Z — Clarity Gate plugin from this directory.
#
# Z is markdown-first, so it can run under more than one CLI harness:
#
#   • Claude Code — registered as a local plugin marketplace, then installed as the `z` plugin.
#   • Codex       — the three skills are rendered into ~/.codex/prompts/z-*.md custom prompts
#                   and a managed block is added to ~/.codex/AGENTS.md. Codex has no plugin
#                   marketplace and no ${CLAUDE_PLUGIN_ROOT}, so the skill text is copied with
#                   that variable resolved to this checkout's absolute path.
#
# Usage:
#   ./install.sh            # auto: install into every supported CLI found on PATH
#   ./install.sh claude     # Claude Code only
#   ./install.sh codex      # Codex only
#   ./install.sh all        # both, and error if either CLI is missing
#
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

TARGET="${1:-auto}"

# ----------------------------------------------------------------------------- Claude Code

install_claude() {
  if ! command -v claude >/dev/null 2>&1; then
    echo "error: 'claude' CLI not found on PATH. Install Claude Code first: https://claude.com/claude-code" >&2
    return 1
  fi

  echo "→ [claude] Registering local plugin marketplace: $HERE"
  claude plugin marketplace add "$HERE"

  echo "→ [claude] Installing plugin: z@z"
  claude plugin install z@z

  echo "✓ [claude] Z — Clarity Gate installed. Try:  z gate \"<goal>\""
}

# ----------------------------------------------------------------------------- Codex

# Render one skill's SKILL.md into a Codex custom prompt:
#   - strip the leading YAML frontmatter (Codex uses its own),
#   - resolve ${CLAUDE_PLUGIN_ROOT} / $CLAUDE_PLUGIN_ROOT to this checkout,
#   - prepend Codex frontmatter (description / argument-hint) and a compatibility note.
# Args: <skill-name> <description> <argument-hint> <out-file>
render_codex_prompt() {
  local name="$1" desc="$2" hint="$3" out="$4"
  local src="$HERE/skills/$name/SKILL.md"

  if [[ ! -f "$src" ]]; then
    echo "error: missing skill source: $src" >&2
    return 1
  fi

  {
    printf -- '---\n'
    printf 'description: %s\n' "$desc"
    [[ -n "$hint" ]] && printf 'argument-hint: %s\n' "$hint"
    printf -- '---\n\n'
    printf '<!-- Generated by Z install.sh from skills/%s/SKILL.md. Do not edit here; edit the source and re-run install.sh. -->\n\n' "$name"
    printf '> **Codex note:** Z is markdown-first and runs the same here. The `${CLAUDE_PLUGIN_ROOT}`\n'
    printf '> paths below are resolved to this machine'"'"'s Z checkout, and every `python3` helper is\n'
    printf '> Python-stdlib-only. If an instruction names a Claude-specific tool (e.g. `AskUserQuestion`),\n'
    printf '> just ask the question in plain chat instead. Anything the user types after the command is\n'
    printf '> the argument (the "goal" / "text").\n\n'

    # Drop the frontmatter block (only if the file starts with ---), then resolve the plugin root.
    awk '
      NR==1 && $0=="---" { infm=1; next }
      infm && $0=="---"  { infm=0; next }
      infm               { next }
                         { print }
    ' "$src" \
      | sed -e "s|\${CLAUDE_PLUGIN_ROOT}|$HERE|g" -e "s|\$CLAUDE_PLUGIN_ROOT|$HERE|g"
  } > "$out"

  echo "  • $(basename "$out")"
}

# Insert/replace the managed Z block in ~/.codex/AGENTS.md (idempotent).
update_codex_agents() {
  local agents="$1"
  local tmp
  tmp="$(mktemp)"

  # Copy over everything except any previous managed block.
  if [[ -f "$agents" ]]; then
    awk '
      /<!-- Z:BEGIN/ { skip=1 }
      !skip          { print }
      /<!-- Z:END/   { skip=0 }
    ' "$agents" > "$tmp"
    # Ensure a trailing blank line before we append.
    [[ -s "$tmp" ]] && printf '\n' >> "$tmp"
  fi

  cat >> "$tmp" <<EOF
<!-- Z:BEGIN (managed by Z install.sh — do not edit inside this block) -->
## Z — Clarity Gate commands

This machine has the Z Clarity Gate installed for Codex. When the user types one of these
inputs (or the natural-language trigger), run the matching custom prompt from ~/.codex/prompts/:

| Input | Prompt |
|-------|--------|
| \`z gate ...\`, "clarity gate", "run the gate", "게이트" | \`/z-gate\` |
| \`z score ...\` | \`/z-score\` |
| \`z card\` | \`/z-card\` |

Z blocks implementation until \`ambiguity <= 0.20\`, then freezes an immutable spec card to the
target project's \`.z/spec-cards/\`. It has no backend — the harness does the scoring by
following the prompt's rubric. Plugin root: $HERE
Deterministic helpers (hashing, validation, caches) are Python-stdlib-only under $HERE/scripts/.
<!-- Z:END -->
EOF

  mv "$tmp" "$agents"
}

install_codex() {
  if ! command -v codex >/dev/null 2>&1; then
    echo "error: 'codex' CLI not found on PATH. Install Codex first: https://github.com/openai/codex" >&2
    return 1
  fi

  local codex_home="${CODEX_HOME:-$HOME/.codex}"
  local prompts_dir="$codex_home/prompts"
  local agents="$codex_home/AGENTS.md"

  mkdir -p "$prompts_dir"

  echo "→ [codex] Rendering custom prompts into $prompts_dir"
  render_codex_prompt gate \
    "Clarity Gate — Socratic interview + ambiguity scoring; freezes an immutable spec card." \
    "<goal>" \
    "$prompts_dir/z-gate.md"
  render_codex_prompt score \
    "One-shot clarity/ambiguity score of a goal or draft spec (no interview, no card)." \
    "<goal or draft spec>" \
    "$prompts_dir/z-score.md"
  render_codex_prompt card \
    "Show the latest frozen Clarity Gate spec card and its lineage." \
    "" \
    "$prompts_dir/z-card.md"

  echo "→ [codex] Updating $agents"
  update_codex_agents "$agents"

  echo "✓ [codex] Z — Clarity Gate installed. Try:  /z-gate <goal>"
}

# ----------------------------------------------------------------------------- Dispatch

case "$TARGET" in
  claude) install_claude ;;
  codex)  install_codex ;;
  all)
    install_claude
    install_codex
    ;;
  auto)
    installed=0
    if command -v claude >/dev/null 2>&1; then install_claude; installed=1; fi
    if command -v codex  >/dev/null 2>&1; then install_codex;  installed=1; fi
    if [[ "$installed" -eq 0 ]]; then
      echo "error: neither 'claude' nor 'codex' found on PATH. Install one, or pass a target: ./install.sh [claude|codex|all]" >&2
      exit 1
    fi
    ;;
  *)
    echo "usage: ./install.sh [claude|codex|all]   (no argument = auto-detect installed CLIs)" >&2
    exit 2
    ;;
esac
